### ISSUE TITLE
[Feature request] Matrix list import.

### ISSUE THREAD

**Issue by cyber-speed** [SBCV/Blender-Matrix-World-Addon#1]
Hi,

Just discovered this nice AddOn, amazing.

Was wondering if it would be possible to import from disk a text list that has a 4x4 matrix in each line all 16 values, that would place a selected object in the scene to those coordinates as the main object.
Next line with a 4x4 matrix value would be its 1st instance, next line would be a 2nd instance so on and so forth, all instances placed based on those coordinates that the 4x4 matrix provide, no matter how many 4x4 matrix values each on its own line that text has they are al instances of the main object that is selected.

0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
etc.

The ability to export multiple selected objects matrix values, each 4x4 matrix in its own line, all 16 values in one line.
Or if no object selected entire imported scene.

Or even if possible, instead of the 4x4 matrix each line has positions, rotations and scale each in its own line like this:

x y z    x y z w    x y z
x y z    x y z w    x y z
x y z    x y z w    x y z
etc

position rotation scale

**Comment by SBCV** [comment]
Hey, this sounds like a reasonable extension. But I think probably it makes more sense to support something like a simple json file. This way one can introduce additional content without breaking compatibility of previous files. 
Are you interested to provide a PR?

**Comment by cyber-speed** [comment]
Hello,

Thank you for responding, much appreciated.

Not being a programmer myself, i wouldn't know what would be best to use for such tasks, hence me requesting the additional feature to be added to your AddOn to work as a batch per say for multiple selections and matrix/transforms values.
Also, I have no knowledge as to what could _PR_ stand for.

**Comment by SBCV** [comment]
A quick google search for "PR github" yields:  
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

A PR (Pull request) is the way how different contributors can work on the same repository.

I've just realized that the batch processing would require a substantial change / extension of the addon. Currently, the inner state of the addon is a single object / a single transformation matrix. For a proper extension of the addon to batch processing, one needs to adjust this state and change the gui (which is currently limited to a single transformation matrix) accordingly - which is probably not feasible.

However, for your special case (i.e. reading multiple transformations) you can achieve what you want with a few lines of code:

```
import bpy
import numpy as np
from mathutils import Vector, Matrix

input_file_path = "/path/to/your/file_name.txt"

template_obj = bpy.context.active_object

with open(input_file_path) as my_file:
    # A line is a string
    for line in my_file:

        # Convert the string to 16 float values
        line_as_floats = [float(num_str) for num_str in line.split(" ")]

        # Build the transformation matrix from the 16 float values
        row_1 = Vector(line_as_floats[0:4])
        row_2 = Vector(line_as_floats[4:8])
        row_3 = Vector(line_as_floats[8:12])
        row_4 = Vector(line_as_floats[12:16])
        mat = Matrix([row_1, row_2, row_3, row_4])

        # Copy template object
        new_obj = template_obj.copy()
        # Set transformation
        new_obj.matrix_world = mat
        # Link new object to collection (make it available in blenders gui)
        bpy.context.collection.objects.link(new_obj)
```

And here  "/path/to/your/file_name.txt" contains the transformations, for example:

```
7.175281047821044922e-01 1.873531341552734375e-01 6.708592772483825684e-01 -1.416574716567993164e-01 -6.950705647468566895e-01 2.549041807651519775e-01 6.722356677055358887e-01 1.838565230369567871e+00 -4.505937546491622925e-02 -9.486425518989562988e-01 3.131245672702789307e-01 1.751830577850341797e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00
9.751921296119689941e-01 1.991515010595321655e-01 9.663815051317214966e-02 -7.319483160972595215e-01 -2.021794319152832031e-01 6.235743165016174316e-01 7.551679015159606934e-01 3.402235507965087891e+00 9.013175964355468750e-02 -7.559720873832702637e-01 6.483691334724426270e-01 2.701091527938842773e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00
```

Make sure you select an object before running the script in blender (e.g. the default cube).

I'm afraid that for executing tasks like this, there is no way around some programming. But don't be afraid, there are a lot of good sources online. And stackoverflow provides a lot of answers to almost all standard tasks.

**Comment by cyber-speed** [comment]
Thank you for the explanation.

The python code works great for the 4x4 matrix.

Do you happen to have an example for 3x4 matrix 12 values, as well as for x y z x y z w x y z transforms?
Or a link as to where you go that 4x4 example above? I'm not sure what to google to get what i need, while searching i could not find anything that even resembles the code example above, as by modifying for instance the code above for 3x4 12 values matrix i get a mismatch error as 4x4 expected values not 3x4 in Blender.
This does not work:

        row_1 = Vector(line_as_floats[0:3])
        row_2 = Vector(line_as_floats[3:6])
        row_3 = Vector(line_as_floats[6:9])
        row_4 = Vector(line_as_floats[9:12])

**Comment by SBCV** [comment]
As you can see in the [documentation](https://docs.blender.org/api/current/bpy.types.Object.html?highlight=matrix_world#bpy.types.Object.matrix_world), `matrix_world` is a 4x4 matrix. So you can not assign a matrix with a different size.

But Blender offers alternative ways of setting specific object attributes (like location, rotation or size). See for example [this stackoverflow](
https://blender.stackexchange.com/questions/61868/scaling-a-newly-made-cube) entry to see how to set the scale.

I highly recommend play with the different commands in the "Python Console" in Blender. Thus, you can immediately see the effect of a specific command.
